<a href="https://colab.research.google.com/github/preetamjumech/Optimization-Problem/blob/main/Optimization_Problem_24_01_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from scipy.optimize import linear_sum_assignment

# Maximizing Profit

In [ ]:
matrix = np.array([[5,7,11,6,7],
                  [8,5,5,6,5],
                  [6,7,10,7,3],
                  [10,4,8,2,4]])

In [ ]:
np.amax(matrix)

11

In [ ]:
np.max(matrix)

11

In [ ]:
cost_matrix = []
for row in matrix:
  cost_row = []
  for col in row:
    cost_row += [np.max(matrix)-col]
  cost_matrix += [cost_row]

In [ ]:
cost_matrix

[[6, 4, 0, 5, 4], [3, 6, 6, 5, 6], [5, 4, 1, 4, 8], [1, 7, 3, 9, 7]]

In [ ]:
d_row = np.zeros(5, dtype = int)
d_row

array([0, 0, 0, 0, 0])

In [ ]:
d_row = np.zeros((5,), dtype = int)
d_row

array([0, 0, 0, 0, 0])

In [ ]:
new_cost_matrix = np.vstack([cost_matrix,d_row])
new_cost_matrix

array([[6, 4, 0, 5, 4],
       [3, 6, 6, 5, 6],
       [5, 4, 1, 4, 8],
       [1, 7, 3, 9, 7],
       [0, 0, 0, 0, 0]])

In [ ]:
row_ind, col_ind = linear_sum_assignment(new_cost_matrix)
print(row_ind)
print(col_ind)

[0 1 2 3 4]
[2 3 1 0 4]


In [ ]:
profit = np.vstack([matrix,d_row])[row_ind,col_ind]
profit

array([11,  6,  7, 10,  0])

In [ ]:
total_profit = np.vstack([matrix,d_row])[row_ind,col_ind].sum()
total_profit

34

In [ ]:
m = np.array([[5,7,11],
              [8,5,5]
            ])
m[0,1]

7

# Linear Programming, Sensitivity Analysis

In [ ]:
!pip install pulp

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.7/17.7 MB 27.1 MB/s eta 0:00:00


In [ ]:
import pandas as pd
import pulp as p

In [ ]:
model = p.LpProblem("myproblem",p.LpMaximize)

In [ ]:
x1 = p.LpVariable("x1", lowBound = 0)
x2 = p.LpVariable("x2", lowBound = 0)
x3 = p.LpVariable("x3", lowBound = 0)

In [ ]:
model += 2*x1 + x2 + x3

In [ ]:
model += 3*x1 + x2 + x3 <= 60
model += x1 - x2 + 2*x3 <= 10
model += x1 + x2 - x3 <= 20

In [ ]:
model.solve()

1

In [ ]:
# model.writeLP("myproblem.lp")
# model.solve(p.GLPK(options = ['--ranges sensit.sen']))
model.solve()

1

In [ ]:
p.LpStatus

{0: 'Not Solved',
 1: 'Optimal',
 -1: 'Infeasible',
 -2: 'Unbounded',
 -3: 'Undefined'}

In [ ]:
print("model status: {}".format(p.LpStatus[model.status]))

model status: Optimal


In [ ]:
p.value

<function pulp.utilities.value(x)>

In [ ]:
print("objective: {}".format(p.value(model.objective)))

objective: 60.0


In [ ]:
for v in model.variables():
  print(v.name, "-", v.varValue, "reduced cost: ", v.dj)

x1 - 0.0 reduced cost:  -1.0
x2 - 36.666667 reduced cost:  -0.0
x3 - 23.333333 reduced cost:  -0.0


In [ ]:
s = [{"name": name, "shadow price": c.pi, "slack": c.slack} for name, c in model.constraints.items()]
s

[{'name': '_C1', 'shadow price': 1.0, 'slack': -0.0},
 {'name': '_C2', 'shadow price': -0.0, 'slack': -0.0},
 {'name': '_C3', 'shadow price': -0.0, 'slack': 6.666667}]

In [ ]:
pd.DataFrame(s)

name  shadow price     slack
0  _C1           1.0 -0.000000
1  _C2          -0.0 -0.000000
2  _C3          -0.0  6.666667